### ISSUE TITLE
Does this boot on device load?

### ISSUE THREAD

**Issue by nh43de** [m4tt1mus/BlazorMirror#3]
I love the concept. Question: how might you be able to get this to boot on device load so that it's always running?

**Comment by m4tt1mus** [comment]
This currently isn't supported. I'm pretty busy right now so don't plan to tackle it anytime soon but would love it if thats how it worked. There are multiple ways to start a program on startup: 
https://www.raspberrypi.org/forums/viewtopic.php?t=132637
If you would like to take a look and submit a PR. I'd be happy to take a look at it and merge it if it works!

**Comment by m4tt1mus** [comment]
Doesn't seem to work 100%

**Comment by m4tt1mus** [comment]
The service seems to start via the cronjob, but the browser doesn't
